# Navnet på denne automatiske arbejdsgang på GitHub Actions
name: Find the Golden Path

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp

      # Scriptet leder efter din 'sftp-test' mappe på alle tre niveauer
      - name: Locate sftp-test folder
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -e "set sftp:connect-program 'ssh -a -x -o StrictHostKeyChecking=no'; echo '=== KIGGER I RODEN ==='; ls; echo '=== KIGGER I AMATEULYTICS.COM ==='; ls amateulytics.com; echo '=== KIGGER I FILES ==='; ls amateulytics.com/files; quit" -u $FTP_USERNAME,$FTP_PASSWORD sftp://ssh.c4ew2s88y.service.one